### ISSUE TITLE
Viết markdown cho Bảng `ProductImages` mới được thêm vào trong source. (Checkout sang branch dev trước khi làm)

### ISSUE THREAD

**Issue by imnortheastt** [Bacdong/applestore_dotnet_core#2]
-> applestore/Data/Conventions/global.md

* Lưu ý: Viết đúng thứ tự các bảng trong "markdown global (global.md)". Thứ tự đúng như thứ tự sắp xếp các file trong "applestore/Data/Entities".

**Comment by imnortheastt** [comment]
Deadline: 23h59p 29/10/2020

**Comment by BuiTrungHau1312** [comment]
take task kkk.
